### ISSUE TITLE
Enhancement | Add language filters

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#2]

**Comment by Amar995** [comment]
@aadeshkulkarni assign me and tell me issue details

**Comment by KrupaPanchal2527** [comment]
@aadeshkulkarni This is done in [commit](https://github.com/aadeshkulkarni/first-issues/commit/b9ab1c1bcf8694e5573dcbcefe98ac604aa2a7c3).
