### ISSUE TITLE
Bug | Language Filters are sometimes not visible

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#21]
<img width="1790" alt="Screenshot 2024-06-28 at 9 22 34 PM" src="https://github.com/aadeshkulkarni/first-issues/assets/67855887/f83d1ed2-8637-4e0b-9d74-35835fe1bf96">

**Comment by aadeshkulkarni** [comment]
This is probably happening because the lang-filter api is called before the repo api. 
The repo api sets up the store. But since lang-filter API tries fetching from store before that, it returns empty data.

**Comment by vverma022** [comment]
I'll try to look into this

**Comment by aadeshkulkarni** [comment]
@vverma022 - Found the root cause of the issue ?

**Comment by aadeshkulkarni** [comment]
This is fixed as part of [commit](https://github.com/aadeshkulkarni/first-issues/commit/f22f1142756551157abc5d83a17d2dc101f9cf95)
