### ISSUE TITLE
Bug | Theme icon | Hover state

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#23]
### Issue

The black background on hover is applied only on the icon, should be applied on the entire icon container. Same for light mode.

### Screenshot

![Screenshot 2024-07-03 at 8 17 26 PM](https://github.com/aadeshkulkarni/first-issues/assets/67855887/1e62be6a-174f-4ce2-a9cd-b534dabfb44f)

**Comment by 0xprathamesh** [comment]
Hi @aadeshkulkarni fixed the issue on local environment by removing some styles.you can assign me the task.
Below are some attachments how i fixed it.

#### Before
![Screenshot 2024-07-12 at 9 59 10 AM](https://github.com/user-attachments/assets/395e6141-ba87-4c1b-8d2a-05e794578814)


#### After
![Screenshot 2024-07-12 at 9 53 11 AM](https://github.com/user-attachments/assets/6ca67d42-c9c5-4a86-9efd-2f8459190e69)

**Comment by aadeshkulkarni** [comment]
looks good, please raise a PR
