### ISSUE TITLE
Enhancement | Feedbacks 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#24]
- Add a new route `/feedback-list`
 - Display feedbacks as a list / card (sorted by latest at the top)
 - Keep it simply initially, be creative if time permits.

**Comment by 0xprathamesh** [comment]
Hey @aadeshkulkarni I'm done with the Enhancement of Feedbacks Page.you can assign this task to me.


<img width="1440" alt="Screenshot 2024-07-13 at 2 14 52 PM" src="https://github.com/user-attachments/assets/5417972d-0e23-416b-8567-f8cc0ff97fb3">


<img width="1440" alt="Screenshot 2024-07-13 at 2 19 12 PM" src="https://github.com/user-attachments/assets/1afbd5d2-d1d5-47ca-ba98-51dbb6dca58d">
