### ISSUE TITLE
Enhancement | Contributors page

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#26]
- `/contributors` route.
- Same as https://www.figuringout.life/contributors, but better UI/UX.
- Use Github api to fetch contributors list.

**Comment by 0xprathamesh** [comment]
Hi @aadeshkulkarni i am done with the enhancement of contributors page. Plz can u assign me the issue.
![Screenshot 2024-07-12 at 12 16 45 AM](https://github.com/aadeshkulkarni/first-issues/assets/100022693/1c77961e-bb30-4f75-8847-0a2cfabe96b5)
![Screenshot 2024-07-12 at 12 16 32 AM](https://github.com/aadeshkulkarni/first-issues/assets/100022693/e65df510-f872-449a-9617-7d0d030fa7df)

**Comment by aadeshkulkarni** [comment]
Thank you for contribution!
