### ISSUE TITLE
Enhancement | Dark / Light mode

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#3]

**Comment by vverma022** [comment]
Could this be implemented with Shadcn UI as it's a new project.

**Comment by aadeshkulkarni** [comment]
Yes, Shadcn is already added to the project.

**Comment by vverma022** [comment]
I'd like to implement it. Any theme specifications ?

**Comment by aadeshkulkarni** [comment]
@vverma022 - Sorry. This issue has been resolved. the feature is live.
