### ISSUE TITLE
Enhancement | Clear filters

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#32]
User should be able to clear the filters they've selected. 

If user clicks on filtered language, the list should reset.
If user clicks on sorted item, the list should reset.

**Comment by aadeshkulkarni** [comment]
This works for langugage, doesn't work for sorting.

**Comment by 0xprathamesh** [comment]
Hey @aadeshkulkarni ,
done with the Enhancement of clear filters for the sorted item. u can assign this task to me.
