### ISSUE TITLE
Bug | Frontend Fix | Loading state 

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#44]
- Remove the loading icon. It does not go well with the aesthetics.
- Increase the loading shimmer items in the list so that it takes up the space till the bottom of the screen.

![Screenshot 2024-09-11 at 7 10 18 PM](https://github.com/user-attachments/assets/3dd30e16-e675-4056-b018-f9b2a9ecee1a)

**Comment by 0xprathamesh** [comment]
Hey @aadeshkulkarni can u assign it to me i knew how to solve this issue!

**Comment by aadeshkulkarni** [comment]
@0xprathamesh - sure. Assigned it to you.
