### ISSUE TITLE
Enhancement | Add Sorting ability

### ISSUE THREAD

**Issue by KrupaPanchal2527** [aadeshkulkarni/first-issues#5]
Add the ability to sort data based on -
1. Last active
2. Stars
3. Number of issues

**Comment by aadeshkulkarni** [comment]
@KrupaPanchal2527 - Okay if I pick this up ?

**Comment by KrupaPanchal2527** [comment]
Sure. Assigned to you.

**Comment by aadeshkulkarni** [comment]
Will work on this once #15 changes are merged with main. Might need to rework otherwise.

**Comment by aadeshkulkarni** [comment]
Sorting with default setup is done.

Last active - asc (latest first)
Stars - desc
Issues - desc
