### ISSUE TITLE
Enhancement | User feedback

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#7]
Users should be able to provide feedback to the application so that we can iteratively improve the app.

### What ?
A Feedback container with the following
- Name (optional)
- Feedback (Textarea)
- A submit button

The feedback should get uploaded to Mongo DB. Use Mongoose or Prisma as the ORM.

This is a low priority enhancement at the current stage of application development.

**Comment by ssk090** [comment]
Hey @aadeshkulkarni, I have implemented a basic feedback form here: https://github.com/aadeshkulkarni/first-issues/pull/20

Thanks!
