### ISSUE TITLE
Bug | Hide the scrollbar but keep the functionality

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/first-issues#8]
Either hide the scroll or make it looker.

### Screenshot:

![Screenshot 2024-06-25 at 12 05 48 AM](https://github.com/aadeshkulkarni/first-issues/assets/67855887/1bc91f5c-a1f7-47e9-83e4-03cba85fe53e)

**Comment by ssk090** [comment]
Hey @aadeshkulkarni, I have raised a PR for the same: https://github.com/aadeshkulkarni/first-issues/pull/17
please feel free to check this out. Thanks!
